from __future__ import annotations

from pathlib import Path

from ..artifacts import StageManifest, write_manifest as write_stage_manifest
from ..nmc_core.checks import validate_pairs as validate_nmc_pairs
from ..nmc_core.model import MINIMUM_PAIRS, NMCManifestPair
from ..shell import symlink_force, write_text
from .manifest import write_manifest
from .model import BflowPair, compact_time


def validate_pairs(pairs: list[BflowPair], *, minimum_pairs: int = MINIMUM_PAIRS) -> None:
    """Reject incomplete, duplicate or missing f048/f024 inputs before BFLOW."""
    validate_nmc_pairs(
        [NMCManifestPair(pair.valid_time, pair.f048, pair.f024) for pair in pairs],
        minimum_pairs=minimum_pairs,
    )


def link_pair_inputs(workspace: Path, pairs: list[BflowPair]) -> None:
    inputs = workspace / "inputs"
    for pair in pairs:
        vdir = inputs / compact_time(pair.valid_time)
        symlink_force(pair.f048, vdir / "f048.nc")
        symlink_force(pair.f024, vdir / "f024.nc")
        write_text(vdir / "pair.env", f"VALID_TIME={pair.valid_time}\nF048={pair.f048}\nF024={pair.f024}\n")


def write_readme(workspace: Path, pairs: list[BflowPair]) -> None:
    lines = [
        "# Bflow preprocessing workspace",
        "",
        "Generated by `mpas-bmatrix build`.",
        "",
        "## Inputs",
        "",
    ]
    for pair in pairs:
        lines.extend([f"- `{pair.valid_time}`", f"  - f048: `{pair.f048}`", f"  - f024: `{pair.f024}`"])
    lines.extend(
        [
            "",
            "## Run",
            "",
            "```bash",
            "mpas-bmatrix build --from-stage bflow --to-stage bflow --bflow-workspace $(pwd) --clean",
            "```",
            "",
            "Products are written below `output/YYYYMMDDHH/`.",
            "The current Python runner no longer generates Python helper scripts or a master shell script.",
        ]
    )
    write_text(workspace / "README.md", "\n".join(lines) + "\n")


def prepare_workspace(
    config,
    pairs: list[BflowPair],
    workspace: Path,
    force: bool = False,
    minimum_pairs: int = MINIMUM_PAIRS,
) -> Path:
    workspace.mkdir(parents=True, exist_ok=True)
    (workspace / "scripts").mkdir(exist_ok=True)
    (workspace / "logs").mkdir(exist_ok=True)
    (workspace / "output").mkdir(exist_ok=True)

    validate_pairs(pairs, minimum_pairs=minimum_pairs)
    write_manifest(workspace / "manifest.tsv", pairs)
    write_stage_manifest(
        StageManifest(
            stage="bflow",
            workspace=str(workspace.resolve()),
            inputs={"pair_manifest": str((workspace / "manifest.tsv").resolve())},
            outputs={"output_root": str((workspace / "output").resolve())},
            metadata={"members": len(pairs), "valid_times": [pair.valid_time for pair in pairs]},
            status="prepared",
        )
    )
    link_pair_inputs(workspace, pairs)
    write_readme(workspace, pairs)
    return workspace
